# ---- Ekran ----
SCREEN_W = 1800
SCREEN_H = 1000

# ---- Topologia ----
TORUS = 0
CYLINDER = 1
MOBIUS = 2
KLEIN = 3
SPHERE = 4
TOPOLOGY_NAMES = {0: "TORUS", 1: "CYLINDER", 2: "MOBIUS", 3: "KLEIN", 4: "SPHERE"}
TOPOLOGY_CHANGE_WAVES = 4  # co ile fal zmiana topologii

# ---- Statek ----
THRUST = 300.0
FRICTION = 80.0
ROT_SPEED = 4.0
MAX_SPEED = 350.0
BRAKE_FORCE = 600.0
SHIP_RADIUS = 12
SHIP_VERTS = [(0, -18), (-12, 12), (12, 12)]
SHIP_SIZE = 18
FLAME_VERTS = [(-7, 12), (0, 28), (7, 12)]
STRAFE_SPEED = 200.0

# ---- Heat system ----
HEAT_THRUST_RATE = 0.10
HEAT_SHOOT_RATE = 0.03
HEAT_DECAY_RATE = 0.12
HEAT_OVERDRIVE = 0.75
HEAT_OVERHEAT = 1.0
HEAT_COOLDOWN_TIME = 2.0
HEAT_TRAIL_DAMAGE_RADIUS = 8

# ---- Pociski ----
BULLET_SPEED = 500.0
BULLET_RADIUS = 2.0
BULLET_LIFETIME = 1.5
MAX_BULLETS = 6
SHOOT_COOLDOWN = 0.15
BOUNCING_BOUNCES = 3
HOMING_TURN_RATE = 2.0
GRAVITY_BOMB_RADIUS = 160
GRAVITY_BOMB_STRENGTH = 25000
GRAVITY_BOMB_DURATION = 2.5

# ---- Moduly broni ----
MAX_MODULE_SLOTS = 4

# ---- Asteroidy ----
ASTEROID_SIZES = {
    "large":  (45, 30, 70, 11),
    "medium": (25, 50, 120, 9),
    "small":  (12, 80, 180, 7),
}
ASTEROID_JITTER = 0.4
ASTEROID_ROT_MIN = 0.3
ASTEROID_ROT_MAX = 1.5
ASTEROID_COUNT = 8
ASTEROID_POINTS = {"large": 20, "medium": 50, "small": 100}
ASTEROID_SPECIAL_CHANCE = 0.25

# Crystal asteroid
CRYSTAL_HP = 4
CRYSTAL_POINTS_MULT = 5

# ---- Power-upy ----
POWERUP_DROP_CHANCE = 0.25
POWERUP_RADIUS = 14
POWERUP_LIFETIME = 8.0
POWERUP_EFFECT_DURATION = 8.0

# ---- UFO ----
UFO_SPAWN_INTERVAL_MIN = 25.0
UFO_SPAWN_INTERVAL_MAX = 40.0
UFO_SHOOT_INTERVAL = 1.5
UFO_AIM_ERROR = 0.3
UFO_POINTS_LARGE = 200
UFO_POINTS_SMALL = 1000

# ---- Portale / Wormhole ----
PORTAL_SPAWN_INTERVAL_MIN = 18.0
PORTAL_SPAWN_INTERVAL_MAX = 35.0
PORTAL_LIFETIME = 14.0
PORTAL_RADIUS = 28
PORTAL_ACTIVATION_RADIUS = 22
PORTAL_COOLDOWN = 0.5
PORTAL_MAX_PAIRS = 3

# ---- Gravity wells ----
GRAV_WELL_SPAWN_INTERVAL_MIN = 28.0
GRAV_WELL_SPAWN_INTERVAL_MAX = 50.0
GRAV_WELL_LIFETIME = 18.0
GRAV_WELL_ATTRACT_RADIUS = 180
GRAV_WELL_STRENGTH = 18000
GRAV_WELL_CORE_RADIUS = 12
GRAV_WELL_VISUAL_RADIUS = 20

# ---- Hunter drone ----
HUNTER_SPEED = 130
HUNTER_RADIUS = 9
HUNTER_POINTS = 500
HUNTER_SHOOT_INTERVAL = 2.5
HUNTER_AIM_ERROR = 0.15
HUNTER_HP = 2

# ---- Boss ----
BOSS_WAVE_INTERVAL = 5
BOSS_BEHEMOTH_HP = 30
BOSS_BEHEMOTH_RADIUS = 80
BOSS_QUEEN_HP = 20
BOSS_QUEEN_RADIUS = 35
BOSS_QUEEN_SPAWN_INTERVAL = 3.0
BOSS_MIRROR_HP = 15

# ---- Wave system ----
WAVE_BASE_ASTEROIDS = 8
WAVE_ASTEROID_INCREMENT = 2
WAVE_EVENT_INTERVAL_MIN = 12.0
WAVE_EVENT_INTERVAL_MAX = 25.0
WAVE_EVENT_DURATION = 4.0

# ---- Swarm ----
SWARM_COUNT = 12
SWARM_SPEED = 250
SWARM_RADIUS = 6

# ---- Perki ----
PERK_CHOICES = 3

# ---- Particle ----
PARTICLE_FRICTION = 0.97

# ---- Screen shake ----
SHAKE_DECAY = 5.0

# ---- Combo ----
COMBO_TIMEOUT = 2.0

# ---- Gra ----
START_LIVES = 3
RESPAWN_INVULN_TIME = 2.0
SAFE_SPAWN_RADIUS = 150

# ---- Scoring ----
VELOCITY_SCORE_BONUS = 0.005
DISTANCE_SCORE_BONUS = 0.002
WRAP_SCORE_PER_WRAP = 0.05
WRAP_SCORE_DECAY = 0.03

# ---- Multiplayer respawn ----
MP_RESPAWN_SCORE = 10000       # points to collect to respawn partner
MP_RESPAWN_TIMER = 120.0       # seconds until auto-respawn
MP_RESPAWN_MODES = ["wave", "score", "timer"]

DEBUG = False
